const $=s=>document.querySelector(s), scenesEl=$('#scenes'), key='scenecraft-v1';
let state=JSON.parse(localStorage.getItem(key)||'null')||{title:'Mi próximo video',goal:'Conseguir guardados',format:'Demostración',scenes:[]};
const hooks=['La parte que nadie muestra de…','Esto parecía imposible hasta que cambié una cosa.','Antes de pagar por eso, mira esto.','Probé este método durante siete días.','El error silencioso que arruina tu resultado.','Así se ve el antes y después en 20 segundos.'];
function save(){state.title=$('#title').value;state.goal=$('#goal').value;state.format=$('#format').value;localStorage.setItem(key,JSON.stringify(state));}
function render(){scenesEl.innerHTML='';state.scenes.forEach((s,i)=>{let d=document.createElement('article');d.className='scene';d.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><textarea aria-label="Escena ${i+1}" placeholder="Qué se ve / qué se oye">${s.text}</textarea><input type="number" min="1" max="90" value="${s.seconds}" aria-label="Segundos"><button class="del" aria-label="Eliminar">×</button>`;d.querySelector('textarea').oninput=e=>{s.text=e.target.value;save()};d.querySelector('input').oninput=e=>{s.seconds=Math.max(1,+e.target.value||1);save();metrics()};d.querySelector('.del').onclick=()=>{state.scenes.splice(i,1);save();render()};scenesEl.appendChild(d)});$('#empty').hidden=state.scenes.length>0;metrics()}
function metrics(){$('#count').textContent=state.scenes.length;$('#total').textContent=state.scenes.reduce((a,s)=>a+(+s.seconds||0),0)}
function addScene(text='',seconds=4){state.scenes.push({text,seconds});save();render()};window.addScene=addScene;
$('#add').onclick=()=>addScene();['title','goal','format'].forEach(id=>$('#'+id).oninput=save);
$('#template').onclick=()=>{let t={Demostración:[['Resultado primero: muestra el cambio',2],['Problema en una frase',4],['Proceso: paso 1',5],['Proceso: paso 2',5],['Prueba / detalle',4],['Acción final',3]],Historia:[['Antes: una imagen concreta',4],['El momento de tensión',6],['La decisión que cambió todo',7],['Después: prueba visible',6],['Aprendizaje',5]],Opinión:[['Postura inesperada',3],['Contexto',5],['Evidencia uno',6],['Evidencia dos',6],['Objeción',5],['Conclusión',4]],Tutorial:[['Resultado final',3],['Materiales',4],['Paso 1',6],['Paso 2',6],['Paso 3',6],['Error común',4],['Cierre',3]]};state.scenes=t[$('#format').value].map(x=>({text:x[0],seconds:x[1]}));save();render()};
$('#shuffle').onclick=()=>$('#hook').textContent='“'+hooks[Math.floor(Math.random()*hooks.length)]+'”';
$('#export').onclick=()=>download(`${slug(state.title)}.json`,JSON.stringify(state,null,2),'application/json');
$('#print').onclick=()=>{let rows=state.scenes.map((s,i)=>`${i+1}. ${s.text} — ${s.seconds}s`).join('\n');let content=`SCENECRAFT — HOJA DE RODAJE\n${state.title}\nObjetivo: ${state.goal}\nFormato: ${state.format}\nDuración: ${state.scenes.reduce((a,s)=>a+s.seconds,0)}s\n\n${rows}`;download(`${slug(state.title)}-rodaje.txt`,content,'text/plain')};
function slug(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'proyecto'}function download(n,c,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#title').value=state.title;$('#goal').value=state.goal;$('#format').value=state.format;render();

document.querySelector('.buy').onclick=()=>alert('Conecta aquí el enlace de checkout de Whop cuando el producto esté creado.');
